name: rental-car-api-compose

version: "3.8"

services:
  backend:
    build:
      context: ../admin-a/backend/app
      dockerfile: Dockerfile
    volumes:
      - ../admin-a/backend/app:/app
    ports:
      - "8000:80"
    # user: "devuser"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://fastapiuser:fastapipass@db:5432/fleamarket

  db-model:
    build:
      context: ../database/app
      dockerfile: Dockerfile
    volumes:
      - ../database/app:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: api-db
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: fastapiuser
      MYSQL_PASSWORD: fastapipass
      MYSQL_DATABASE: fleamarket
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    hostname: mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=fastapiuser
      - PMA_PASSWORD=fastapipass
    depends_on:
      - db
