name: Flake8

on:
  pull_request:
    paths:
      - "admin-a/backend/app/**"

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        working-directory: admin-a/backend/app
        run: |
          flake8 domain --config=.flake8 --count --show-source --statistics
          flake8 use_cases --config=.flake8 --count --show-source --statistics
          flake8 repository --config=.flake8 --count --show-source --statistics
          flake8 schemas --config=.flake8 --count --show-source --statistics
          flake8 routers --config=.flake8 --count --show-source --statistics
