name: Flake8

on:
  pull_request:
    paths:
      - "admin-a/backend/app/domain/**"
      - "admin-a/backend/app/use_cases/**"
      - "admin-a/backend/app/repository/**"
      - "admin-a/backend/app/schemas/**"
      - "admin-a/backend/app/routers/**"

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          flake8 admin-a/backend/app/domain --config=.flake8 --count --show-source --statistics
          flake8 admin-a/backend/app/use_cases --config=.flake8 --count --show-source --statistics
          flake8 admin-a/backend/app/repository --config=.flake8 --count --show-source --statistics
          flake8 admin-a/backend/app/schemas --config=.flake8 --count --show-source --statistics
          flake8 admin-a/backend/app/routers --config=.flake8 --count --show-source --statistics
