name: Flake8

on:
  pull_request:
    paths:
      - "multi-admin/admin-a/backend/app/domain/**"
      - "multi-admin/admin-a/backend/app/use_cases/**"
      - "multi-admin/admin-a/backend/app/repository/**"
      - "multi-admin/admin-a/backend/app/schemas/**"
      - "multi-admin/admin-a/backend/app/routers/**"

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # 使用するPythonのバージョンを指定
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          flake8 multi-admin/admin-a/backend/app/domain --count --show-source --statistics
          flake8 multi-admin/admin-a/backend/app/use_cases --count --show-source --statistics
          flake8 multi-admin/admin-a/backend/app/repository --count --show-source --statistics
          flake8 multi-admin/admin-a/backend/app/schemas --count --show-source --statistics
          flake8 multi-admin/admin-a/backend/app/routers --count --show-source --statistics
